### ISSUE TITLE
Option for not deleting images and saving to local file system

### ISSUE THREAD

**Issue by wexotht** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#10]
**Never delete image in BunnyCDN**
When seeking to achieve production like developing environments and saving time and space moving huge media folders between envs, the BunnyCDN storage can be shared for all envs. This is a great feature saving much time and effort.
However, with a single storage, deleting a file on a local env also means deleting the file in production. This is not desirable.

- [x] Option to never delete anything on BunnyCDN
- [x] Do not delete when renaming
- [x] Do not delete when overwriting

Extension of #9 

**Option to save to local file system**
One of the major drawbacks of BunnyCDN is that one essentially have no backup of the images on BunnyCDN since they are never saved to the local file system, meaning server backup utilities cannot handle them. This is to save space of course, which makes sense. However, would be nice with a setting enabled BunnyCDN also to save to the local file system. See patch for example.

- [x] Option for saving images to BunnyCDN AND local file system

Patch we used to solve it temporarily it is attached.

[bunny-save-local-no-delete.txt](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/files/5397440/bunny-save-local-no-delete.txt)

**Comment by tinect** [comment]
Hey @wexotht,

`Never delete image in BunnyCDN` will be introduced in version 2.0.0. Check this PR: #8 

`Option to save to local file system`: I'm not happy with this option. Cause this results in orphaned and spreaded files. I just see this option to use ANY (backup)filesystem, but this would make the upload much slower. Backup bunnycdn could also be some kind of rsyncing via ftp on your own. 🤔

**Comment by wexotht** [comment]
@tinect but isn't that dealers choice and a tradeoff to accept if one wants to? :)
Btw, just thought of something regarding #8 the delete option. If you just return at the top of the delete function it's never removed from cache

**Comment by tinect** [comment]
> but isn't that dealers choice and a tradeoff to accept if one wants to? :)

:-)
> Btw, just thought of something regarding #8 the delete option. If you just return at the top of the delete function it's never removed from cache

Yes, that is intentionally. Cause the cache is just a replication of storage´existence,
