### ISSUE TITLE
Allowed memory exhausted

### ISSUE THREAD

**Issue by unugiyen** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#13]
I have setup a 'regular' shopware cronjob via this documentation: https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/core/scheduled-tasks

It seems this the message:consume runs different commands including the 'media:generate-thumbnails' command.
But I get in the error log this message:

```
10:30:49 CRITICAL  [php] Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 28672 bytes) ["exception" => Symfony\Component\ErrorHandler\Error\OutOfMemoryError { …}]

In ThumbnailService.php line 239:
                                                                              
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate  
  28672 bytes)  
```      
My question is are you guys familiar with this error in combination with this CDN plugin?

**Comment by tinect** [comment]
As discussed in slack: nothing related, increase your memory
