### ISSUE TITLE
Setting bunnyCDN up for several domains

### ISSUE THREAD

**Issue by weestack** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#17]
## Support question
====== What I am trying to achieve ========
If I have a shopware shop, setup with 3 different sales channels, that each use a different theme and domain like the below example:

Sale 1:

- domain: Example1.com
- theme: shopware base

Sale 2:

- domain: hehe.com
- theme: hehe -> extends shopware base

Sale 3:

- domain: what.com
- theme: test -> custom

Common CDN url for all 3 sales channels test.b-cdn.net.

Then what I am trying to setup is:
Sale 1 should get its own theme files from the path example1.com/bundle and example1.com/theme, but all media files uploaded through shopware media should be served through the cdn url. 

Sale 2 should get its own theme files from the path hehe.com/bundle hehe.com/theme, but all media files uploaded through shopware media should be served through the cdn url. 

Sale 1 should get its own theme files from the path what.com/bundle and what.com/theme, but all media files uploaded through shopware media should be served through the cdn url. 

===== ISSUE ======

Common for sale 1, sale 2, and sale 3, is that they all get their /bundles and /theme from example1.com/bundle and example1.com/theme

===== SETUP =====
(all settings are set under plugins/bunnycdn, shopware version is 3.5.x)
GLOBAL CONFIG:
CdnUrl: test.b-cdn.net
storageName: test
CdnHostname: storage.bunnycdn.com
ApiKey: ***
Optional subfolder in CDN: /

Transfer Public filesystem into CDN: true

Transfer Sitemap filesystem into CDN: false

Transfer Theme filesystem into CDN: false

Transfer Asset filesystem into CDN: false

All alternative urls are blank in global config.

Backup files into folder garbage on specific operations onto bunnyCDN filesystem: false

Never delete any file on bunnyCDN-Storage: True

Replicate bunnyCDN operations local: True.

Now from bunnycdn config, I go into each individuel saleschannel eg sale 1 - 3, and set their alternativ url to example1.com, hehe.com and what.com respectively. (These are the only settings altered under the individual sales channels config for bunny cdn.)

but sale 2 and 3 are still fetching /bundle and /theme from example1.com.

**Comment by tinect** [comment]
Hey @weestack,

Sadly that is not possible. Configuring cdn will affect all saleschannels.
That's nothing restricted through the plugin but shopware.

I'll check to hide setting when switching the saleschannel in plugin config.

**Comment by tinect** [comment]
I recognized a bug for the config restriction in the plugin. I'll create a new release which fixes it.

**Comment by weestack** [comment]
@tinect Sounds good, thanks for the quick answer in this matter.

**Comment by tinect** [comment]
Update is now on the way :-)
