### ISSUE TITLE
Media upload via Admin

### ISSUE THREAD

**Issue by haier-dev** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#19]
### Question

Hello, when uploading an image of my shop via the admin, the image is not allowed to be displayed correctly.
The image is created in the CDN storage. If the link of the picture is copied in the admin, this is exactly the path to the picture in the CDN. This structure is correct. However, when I call up this link, I get a 404: No route found for "GET /media/6b/d9/36/1626943107/listing.png

Images that have been uploaded to via FTP can be successfully accessed via your link.

**Comment by tinect** [comment]
Sounds like you have not correctly set the domains. Would you please check them?

**Comment by haier-dev** [comment]
I checked the domains again and I don't see any errors here. The origin url is correct, and Hostname is okay too.

The link does not work for an image that was uploaded via the admin. If I adapt the path behind the domain to an image that was created via the FTP import, I can access this image.

I also checked the shopware.yaml file again.

**Comment by haier-dev** [comment]
admin imported image, image path in ftp correct, image not visible
https://myproject.b-cdn.net/media/56/fe/29/1626954295/2560x2560.jpg

ftp imported image, image path in ftp correct, image visible
https://myproject.b-cdn.net/media/f1/48/28/1620395992/testing.jpg

If i check in bunny.net the path of admin imported file, i can see the image in preview by hovering over over the file. Copy link of file, the link doesnt returns the image.

**Comment by tinect** [comment]
"Domain suspended or not configured". :-(

Please check your config and use the "test"-button in plugin config.

**Comment by shyim** [comment]
Hey,

I am closing this as the issue is stale. Feel free to write again when you checked your credentials in your shop.
