### ISSUE TITLE
replacing image doesn't delete image on bunny

### ISSUE THREAD

**Issue by yunits** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#21]
### Actual behaviour

If I replace an image using backend, the old image still exists.

[At this point I want to thank you guys for your excellent work.]

### Expected behaviour

Old image should be deleted.

### Steps to Reproduce?

Upload an image, save and then replace it.
Now your two URLs are accessible.

**Comment by tinect** [comment]
Hi @yunits,

Can you please check whether the file is really still on the storage at BunnyCDN?
Please keep in mind, bunnycdn uses caches to serve files.

**Comment by tinect** [comment]
Closed due to inactivity
