### ISSUE TITLE
how to migrate already moved sw5 to sw6 best practise

### ISSUE THREAD

**Issue by epagogmbh** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#23]
### Question

hey tinect, 
i have a sw 5 env with already migrated data to bunnycdn, means all pictures of the system are already moved to bunnycdn and its working well. now i try to make an migration to sw6 with their migration assistent. in the part media and seo urls its finding 20.000+ pictures and its working long time to migrate, but in fact it seems not to recognize the right bunny cdn urls of the images. so what is best practise for this migration? first move back all media to shopware5 and than migrate, after that migrate to bunnycdn again or what can i do to use the right media URIs? using the version2 plugin is not working.
maybe there is a good best practise way to do what i want.
thanks for your support
matthias

**Comment by tinect** [comment]
Hey @epagogmbh 

Sadly, I never used the migration of shopware. We import all data fresh from our systems.

Could you please explain your statement `but in fact it seems not to recognize the right bunny cdn urls of the images`?
I mean, what did you find out in fact?

Personally, I'd try to migrate to local storage and then upload the stuff to BunnyCDN.

Best Regards,
Sebastian

**Comment by epagogmbh** [comment]
i found out, that it seems not to regognize the adapter while the migration assistent runs. it transfers the local links and as there are no files locally, its not generating right image links in shopware 6 to show them. and because of another media folder structure, its not easily to replace the url to the old media url. so what i do next is your way: trying to import media images by import/export function instead. will see if that works ;) it would be a practical workaround, thanks for this idea.
