### ISSUE TITLE
[Deployment] Files saved to local media folder (works again after saving plugin configuration)

### ISSUE THREAD

**Issue by MrSnoozles** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#24]
### Question

Hello,

I'm experiencing a huge bug and I think it's related to our deployment setup:
https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/deployment-with-deployer

I installed and configured the plugin correctly, the API data is correct and everything works as expected... until it doesn't anymore.

At one point media via the media manager does not get uploaded to bunny.net anymore but to the local file system instead. To fix this issue, all I have to do is save the plugin configuration again (no need to change anything).

Now I'm wondering what could be the reason for this behaviour? **What happens when the plugin is saved?** Are files written that get lost with each deployment?

Would be glad if anyone had an idea.

**Comment by tinect** [comment]
Hi @MrSnoozles 

correct, there is a subscription onto config.written: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/blob/75c55d171a492a65c9bcaeb02e1f128ac9cc5a17/src/Subscriber/ConfigSubscriber.php#L28

There is a yml-file written into the var-folder which is automatically loaded. Path: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/blob/4513676e4121d641ccae65a89a3d20109651e889/src/FroshPlatformBunnycdnMediaStorage.php#L49

You should add this file to your deployment or calling `system:config:set` onto any relevant setting.

**Comment by Isengo1989** [comment]
@tinect I think there was a thread once upon a time. We added a "shared_files" entry for the file, but it was cleaned after the last pipeline ran. Any idea? 

Shopware 6.4.20.0
PHP 8.1
Deployer 7.1.4

![2023-03-08_07-08](https://user-images.githubusercontent.com/8600299/223633682-9670d483-f06b-404a-94a6-5186b1fb7cb1.png)
![2023-03-08_07-00_1](https://user-images.githubusercontent.com/8600299/223633684-47ea2597-ca71-48cb-956f-9e0f0a148f4a.png)
![2023-03-08_07-00](https://user-images.githubusercontent.com/8600299/223633687-fe45335b-f53f-45e7-aeeb-8b0a012860c1.png)

**Comment by tinect** [comment]
I have currently no managed project with deployer. I would suggest you to check your workflow and deployer itself.
