### ISSUE TITLE
[INFO] bunny.net temporarily disabled S3 protocol, no upload possible

### ISSUE THREAD

**Issue by dsturm** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#25]
### PHP Version

8.1.7

### Shopware Version

6.4.13.0

### Actual behaviour

We're currently having an issue, where we cannot upload / rename any file over this plugin. The log files just showed up

```sh
request.CRITICAL: Uncaught PHP Exception AsyncAws\Core\Exception\Http\ClientException: "HTTP 401 returned for "https://storage.bunnycdn.com/***/media/1d/73/78/1657781118/banner.jpg"." at /***/vendor/async-aws/core/src/Response.php line 422 {"exception":"[object] (AsyncAws\\Core\\Exception\\Http\\ClientException(code: 401): HTTP 401 returned for \"https://storage.bunnycdn.com/***/media/1d/73/78/1657781118/banner.jpg\". at /***/vendor/async-aws/core/src/Response.php:422)"} []
```

After debugging and getting in contact with bunny support, it turns out, they disabled support for the (experimental) S3 protocol.

### Expected behaviour

Upload / rename files works.

### Steps to Reproduce?

- Install, activate and configure Plugin in Shopware
- Upload or rename a file

**Comment by tinect** [comment]
Hey,

Update is on the way.

I've contacted bunnycdn yesterday, and I'm really unhappy 💯 
Their entire system was down for some time, also FTP and storage APIs.
They are calling it "experimental" now because they had these issues. Apart from that, the owner told me we can use this endpoint.

For the moment, they disable the not published S3-endpoint.

See https://github.com/tinect/bunnycdn-s3-flysystem-adapter/issues/2

Thank you.

**Comment by dsturm** [comment]
Thanks @tinect. I'll take a look at the bunnycdn-sftp-flysystem-adapter

**Comment by mateuszfl** [comment]
Why you dont use: https://packagist.org/packages/platformcommunity/flysystem-bunnycdn#v1.3.1 ?
This native interface seems much faster than SFTP.

**Comment by tinect** [comment]
Hey @mateuszfl 
Thank you for bringing this up for me again.

Had seen it in a really early state.

I miss a few features, which are also skipped in tests for flysystemV3:
https://github.com/PlatformCommunity/flysystem-bunnycdn/blob/643467028ca25cea698f8b25b432c2ea808617ef/tests/FlysystemTestSuite.php#L74

Will check it in the next days. Thank you.

**Comment by SwissCommerce** [comment]
Not sure if this is related -> 
![image](https://user-images.githubusercontent.com/108347966/180209006-033021b6-5336-4099-beff-2c7c0ca70c24.png)

**Comment by aliflux-omo** [comment]
Hi. Is the bunny S3 api up yet? I can't find its documentation anywhere.

**Comment by tinect** [comment]
Hey @aliflux-omo No, it was a hidden feature they shut down meanwhile.

**Comment by tinect** [comment]
no, there has been no update. you might want to ask bunny.net when they re-enable S3.
