### ISSUE TITLE
Image Upload in Shop Backend results in "empty" images

### ISSUE THREAD

**Issue by Niklasliedtke** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#31]
### PHP Version

7.4.30

### Shopware Version

6.4.8.1

### Actual behaviour

When we try to upload a new image in the shopware backend it works in general but results in an "empty" image instead of the one we tried to upload. It always looks like this:
![Bildschirmfoto 2022-09-26 um 08 54 57](https://user-images.githubusercontent.com/51081934/192212148-9758b9c0-683f-438f-938a-6280cb80d8f3.png)

When we deactivate the plugin the upload works just fine.

### Expected behaviour

The image that is uploaded is saved correctly.

### Steps to Reproduce?

Open the backend, switch to the media manager, upload any new image (we tried png and jpg).

**Comment by tinect** [comment]
Hey,

The upload process doesn't through an error?
Please check your plugin configuration and verify you don't have anything regaring filesystem set manually in any yml-file within config/packages/*

**Comment by tinect** [comment]
This shows the image is not reachable.

This means, the url is wrong. Please check the called url and the CDN-Url you set in the plugin setting.

**Comment by Niklasliedtke** [comment]
Hi, 
we didn't change the CDN-URL, so it's still set correct in the plugin settings. For existing images everything is fine, the problem ony refers to new uploaded images. Maybe you can reach out to me via liedtke@digitalmanufaktur.com so I can give you access to the shop backend and you can check the behaviour yourself?

**Comment by tinect** [comment]
Please note, that we normally can't give any individual support. Additionally, we can't offer any warranty for anything we touch on your systems.
If it fits for you and I can try to assist you, please contact me directly in shopware community slack.

**Comment by Niklasliedtke** [comment]
Hi Sebastian, thanks for the quick fix in the slack channel. The reason was that the PullZone Connection to the Storage wasn't set in BunnyCDN.
