### ISSUE TITLE
Implemtation Question

### ISSUE THREAD

**Issue by StefanTee** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#32]
### Question

Dear All,

first thanks for providing this free plugin for SW6 - i am about to implement CDN bunny CDN, but evenif i configured and tested the API, the upload to bunny does not get triggered. Could you help me with this simply question. Thanks Stefan 

![Screenshot 2022-10-14 120819](https://user-images.githubusercontent.com/115788829/195823288-d3959e71-e08b-40a0-a016-d64c0b8b7077.png)

**Comment by StefanTee** [comment]
Thanks - yes i was referring to existing and possibly new images.  It looks like i may need professional help to get this running. In case you offer  (paid) CDN implementation services  as well, let me know. Thanks

**Comment by tinect** [comment]
Sadly, not possible while I don't have any business :-(
