### ISSUE TITLE
Plugin installation not possible without theme / assets

### ISSUE THREAD

**Issue by SwissCommerce** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#34]
### PHP Version

8.0.24

### Shopware Version

6.4.16.1

### Actual behaviour

It is not possible to activate the plugin without theme and assets toogled to true

Error: Uncaught Symfony\Component\Asset\Exception\InvalidArgumentException: "" is not a valid URL. in /var/www/shopware/releases/5/vendor/symfony/asset/UrlPackage.php:127

### Expected behaviour

Use plugin without theme being pushed to BunnyCDN

### Steps to Reproduce?

Install plugin freshly on a 6.4.16.1 shop, set all credentials and do not select theme and assets.

**Comment by tinect** [comment]
Hey, will check it this evening. But could it be your APP_URL in env is empty? This is the failover.

**Comment by SwissCommerce** [comment]
Hey, the APP_URL is set 

APP_URL="https://b2b.MYSHOP.de"

**Comment by tinect** [comment]
Could you please check the bunnycdn_config.yml within the var-folder?
There should always be a URL.

If it's really empty, could you please debug this line: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/blob/master/src/Service/ConfigUpdater.php#L53
There should be the named URL.

I think we could check the [EnvironmentHelper](https://github.com/shopware/platform/blob/trunk/src/Core/DevOps/Environment/EnvironmentHelper.php).

**Comment by SwissCommerce** [comment]
```
shopware:
    cdn: { url: 'https://XXXX.b-cdn.net' }
    filesystem: { public: { type: bunnycdn, url: 'https://XXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXX, subfolder: '', apiKey: XXXX-afde-40a8-ad01881a6521-1fd6-XXXXX, useGarbage: false, neverDelete: false } }, sitemap: { type: bunnycdn, url: 'https://XXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXX, subfolder: '', apiKey: XXXX-afde-40a8-ad01881a6521-1fd6-XXXX, useGarbage: false, neverDelete: false } }, theme: { type: bunnycdn, url: 'https://XXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXX, subfolder: '', apiKey: XXXX-afde-40a8-ad01881a6521-1fd6-XXXXX, useGarbage: false, neverDelete: false } }, asset: { type: bunnycdn, url: 'https://XXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXX, subfolder: '', apiKey: XXXX-afde-40a8-ad01881a6521-1fd6-XXX, useGarbage: false, neverDelete: false } } }
```

This is what it looks like when working and this is when I remove for example assets

```
shopware:
    cdn: { url: 'https://XXXXX.b-cdn.net' }
    filesystem: { public: { type: bunnycdn, url: 'https://XXXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXXX, subfolder: '', apiKey: XXXXX-afde-40a8-ad01881a6521-1fd6-XXXXX, useGarbage: false, neverDelete: false } }, sitemap: { type: bunnycdn, url: 'https://XXXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXXX, subfolder: '', apiKey: XXXXX-afde-40a8-ad01881a6521-1fd6-XXXXX, useGarbage: false, neverDelete: false } }, theme: { type: bunnycdn, url: 'https://XXXXX.b-cdn.net/', config: { endpoint: 'https://storage.bunnycdn.com', storageName: XXXXX, subfolder: '', apiKey: XXXXX-afde-40a8-ad01881a6521-1fd6-XXXXX, useGarbage: false, neverDelete: false } }, asset: { type: local, url: false, config: { root: '%kernel.project_dir%/public' } } }
```

Seems like asset -> url being **false** is the issue here.

**Note**: I am using the new flex template.

**Comment by tinect** [comment]
Thank you for the feedback. I've not tested the flex template yet, so I've to ask for your help.

Could you please verify what I mentioned above?

> If it's really empty, could you please debug this line: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/blob/master/src/Service/ConfigUpdater.php#L53
There should be the named URL.

I assume it's false. Could you please check if this helps?
`Shopware\Core\DevOps\Environment\EnvironmentHelper::getVariable('APP_URL')` instead of `getenv('APP_URL')`

**Comment by SwissCommerce** [comment]
@tinect yes this seems to work

![2022-11-02_09-30](https://user-images.githubusercontent.com/108347966/199438957-97ae8be9-bdad-4e5f-b1be-55ebda949f55.png)

Seems like `The reason is that using getenv() and putenv() is strongly discouraged due to the fact that these functions are not thread safe`

![2022-11-02_09-31](https://user-images.githubusercontent.com/108347966/199438982-e0e70b5c-d193-454c-9c4d-1e5f13f4853d.png)

EnviromentHelper seems like the right choice 

https://github.com/shopware/core/blob/752ced62e4b15586fba383b2e4c73815f4612be2/Framework/Adapter/Asset/FallbackUrlPackage.php#L28
