### ISSUE TITLE
Theme config lost

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#42]
### PHP Version

8.1

### Shopware Version

6.4.18

### Actual behaviour

Cannot change/view theme setting (theme editor and no theme in sales channel)

### Expected behaviour

Normal functional

### Steps to Reproduce?

add theme and config theme
install bunnycdn plugin and config
enable filesystem on CDN
![afbeelding](https://user-images.githubusercontent.com/75847795/212767460-229c5b7b-31a3-4e57-853b-9d60b8bc9c13.png)

and the theme setting are gone.

**Comment by tinect** [comment]
Hi,
I've transferred the issue to the correct repository.

Does it help to compile theme and install assets in cli?

**Comment by Tim-VL** [comment]
Hi @tinect,

For the theme Yes. But I still get api errors.
FYI; Theme compiling took almost one hour.
