### ISSUE TITLE
Download / Upload / Unzip

### ISSUE THREAD

**Issue by markeymakey** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#43]
### Question

How is the best practice for downloading large folders from an storage? And how do i unzip an archive after uploading?

**Comment by tinect** [comment]
best practice for downloading: scp/ftp: f.e. `scp -r  STORAGEZONENAME@storage.bunnycdn.com:/ ./mylocalpath`
unzip on storage: not possible, please contact bunnyCDN if you want to give it as feature idea or similar
