### ISSUE TITLE
Strange behaviour with local replication.

### ISSUE THREAD

**Issue by WernerHighflyers** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#44]
### Question

Hi, 
we have a very strange phenomenon.
We have switched on local replication, the files are uploaded correctly to bunnycdn, including the thumbnails.
Locally, however, the original image is saved, so the file is there, but unfortunately 0 bytes in size.
However, the thumbnails are saved correctly locally, 
so it's really very strange.
What could be the reason for this?

But thank's for this plugin!!
Best regards,
Werner Buchert.

**Comment by tinect** [comment]
Hi @WernerHighflyers 

this sounds really strange, while they are using the same code.
I'll try to check it at the next weekend. Could you please tell me:
PHP Version
Plugin Version
Shopware Version

**Comment by WernerHighflyers** [comment]
Hi @tinect

yes, i know, super strange ....

PHP Version: 8.2.1
Plugin Version: 2.3.5
Shopware Version: 6.4.19.0 

Thanks and best regards,
Werner Buchert.

**Comment by tinect** [comment]
Hey, sadly I cannot reproduce this error :-( 
Your disk has enough space? No issues writing other files onto the system?

**Comment by tinect** [comment]
Could you please try with the code from the linked PR?
