### ISSUE TITLE
Errors in the Event Log

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#47]
### Question

Hello,

I have these errors in the Event Log, is this something that comes from the plugin? Ifso, is there an way to fix this?
In the Bunny log there are no error.

![afbeelding](https://user-images.githubusercontent.com/75847795/228871706-9a3d831c-2bcb-43dd-ba1f-8fb001e7b0fc.png)

Thanks,
Tim

**Comment by tinect** [comment]
Hi,
This seems really be unrelated to this plugin. These are just paths for your used cdn url. 

could you please verify it does not occur with this plugin and add some more info about the environment (shopware version, plugin version, ..) .

**Comment by Tim-VL** [comment]
Hi tinect,

At this moment I cannot test since our test-env is down (server replace). Will do that asap when it up again.

Env:
Shopware v6.4.19
Plugin v2.3.6

**Comment by tinect** [comment]
Which filesystems have you set to be transferred to bunnycdn? Did you run theme:compile and assets:install once on click after saving the configuration?

**Comment by Tim-VL** [comment]
All the filesystems are transferred to Bunny. Yes, do the theme compile everytime after theme change/update and the assets install is done after plugin updates.

**Comment by Tim-VL** [comment]
Sorry the late reply!

Still have these errors... I cannot find any relations to anything with these errors. Any idea?
![afbeelding](https://user-images.githubusercontent.com/75847795/230653744-7d9dc080-d665-4d56-8d18-3f49dd167638.png)

**Comment by tinect** [comment]
Sadly, I have no idea, but the default thing: remove any plugin and try again.

**Comment by tinect** [comment]
I'll close here due to inactivity.
