### ISSUE TITLE
404's on thumbnails

### ISSUE THREAD

**Issue by VonZubinski** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#48]
### Question

After using run `scp -r ./public/media STORAGEZONENAME@storage.bunnycdn.com:/` on a new test installation, we had 404 errors showing for all the smaller images in the thumbnails folder.

It was fixed by `scp -r ./public/thumbnail STORAGEZONENAME@storage.bunnycdn.com:/`

Maybe including that step in the manual?

**Comment by tinect** [comment]
It's changed, thank you.
