### ISSUE TITLE
Doesn't work on 6.5

### ISSUE THREAD

**Issue by Chloe-ko** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#50]
### PHP Version

8.1

### Shopware Version

6.5.1.1

### Actual behaviour

I'm not exactly sure what is wrong, however under 6.5 the Plugin does not work.
The installation and configuration goes fine, however, files just do not get actually uploaded to bunny or accessed via such.

I tried this on an updated as well as on a completely fresh install of 6.5, with the same results.
I also tried both the manual download via GitHub as well as the version in the Store, same result.

Also, there is no configuration file being generated in var, as the README says it should be.
The file gets created just fine in Shopware 6.4.
Copying over the generated file from the 6.4 install to the 6.5 install manually causes the admin panel to stop working with a "Shopware is not defined" message in the console, though this might be expected behavior with an old configuration file.

### Expected behaviour

I expect the plugin to cause the BunnyCDN to start being used.

### Steps to Reproduce?

Install a Shopware 6.5 instance, install and configure the plugin, try uploading any media.

**Comment by tinect** [comment]
Hey,

> Also, there is no configuration file being generated in var, as the README says it should be.

are you sure? Because the message you are writing after that shows that you config has been set and the file is accessible.
And you set asset-filesystem to be transferred.

pleade run theme:compile and asset:install on CLI.

**Comment by markeymakey** [comment]
Hi there is there any news for the next updates showpare 6.5.3.0?

**Comment by tinect** [comment]
> Hi there is there any news for the next updates showpare 6.5.3.0?

please open a dedicated issue explaining what you mean. there is a compatible version released.
