### ISSUE TITLE
Multiple Saleschannel config. Avoid CORS Errors

### ISSUE THREAD

**Issue by markeymakey** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#51]
### Question

Hi there,

i today created a 2nd saleschannel with an aliasdomain pointing to my mainshop. If i disable bunny plugin, the url in network tab is correct with the aliasdomain and everything is fine. if i use the plugin, i get CORS errors because in the 2nd shop with the aliasdomain the fonts / assets are loaded from the main url which is wrong. Is bunny not multishop compatibel? 

Thanks and best rgards!
Mark

**Comment by tinect** [comment]
you want to use two different domains?
this is not possible woth shopware. 
you can just have one domain per filesystem.
every filesystem is shared with all saleschannels.

So the URL you set up in bunnycdn is used for every saleschannels.

please check you have confired the plugin woth the bunnycdn-url and the CORS at bunny correctly.

**Comment by markeymakey** [comment]
Hi there

no i just added another saleschannel with it's on domain routed to the public of the mainshop. Nothing special actually, i assigned adifferent theme to the saleschannel and then i am getting CORS. 

How can i set different settings for different saleschannels, is the right question. Sorry for my confused explanation!

**Comment by tinect** [comment]
the answer is: you can't :-( 

such a feature is not supported by shopware.

adding it within this plugin would mean manipulating the output of any html and text-output which will result in slower results.

I suggest you to use the same url.

**Comment by markeymakey** [comment]
okay what a bummer! thank you anyway. i will have to get rid of the lovely bunny then :( i don't want asset paths to be with a "foreign" domain. I don't think (without proof) google doesn't like that either. thanks anyways and take care

**Comment by tinect** [comment]
It is difficult for me to follow your meaning :-( 

what could be the reasons google could not like that you are delivering fast and great content through one domain? I mean, there are shops working with CDNs with same subdomain for different localized shop-domains.

**Comment by markeymakey** [comment]
yes but it is a complete differen domain, no subdomain, and everything like the bundle, scripts, stylesheets, images, videos whatsoever is always a foreign domain. I don't like that idea, tho it could be harmlos to SEO. I appreciate your precious meaning tho you guys from FROSH are awesome.
