### ISSUE TITLE
BunnyCDN images 404 error for thumbnail and media  

### ISSUE THREAD

**Issue by KunBojiMan** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#54]
### Question

Hello FriendsOfShopware,

Your plugin is not running smoothly for our customer "jetzt-kommt-kurth." Unfortunately, some images are not loading completely. We've already contacted BunnyCDN support, but they couldn't help and suggested reaching out to the plugin manufacturer.

I've attached some images of the network tabs where a 404 error appears. If you need access to the admin area, please let us know.

Thank you in advance.

Best regards,

Erwin Walter from 8mylez
![Bildschirmfoto 2023-11-15 um 12 07 03](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/107315000/21419e7a-f562-46a0-ae70-24856960e05e)
![Bildschirmfoto 2023-11-13 um 15 11 59](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/107315000/f7cc0fce-88db-4e14-8d34-506bb4497d30)
![Bildschirmfoto 2023-11-13 um 15 08 30](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/107315000/2f5c4a41-4e14-4f89-8544-d6577e6cdfc8)

**Comment by tinect** [comment]
These urls are from your shop, nothing related to this plugin.
please check:
- clear cache
- check your settings
- check your themes

The url should fit of what you have set into the plugins-config.

**Comment by KunBojiMan** [comment]
Hello Tincet,

I accidentally sent you the wrong screenshot. All images from the CDN folder are being loaded, but some still don't appear. I have already implemented the three points. Some images and folders do not exist in the JKK storage, and as a result, they are not being loaded.

Best regards,
Erwin

![Bildschirmfoto 2023-11-15 um 12 57 39](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/107315000/7f578716-fe33-4c2e-bafa-6addb4e46321)

**Comment by tinect** [comment]
@KunBojiMan we close here due to inactivity.
