### ISSUE TITLE
Broken Images in Shopware 6.5.7.1 after Update

### ISSUE THREAD

**Issue by Lukaloco** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#55]
### PHP Version

8.2

### Shopware Version

6.5.7.1

### Plugin Version

3.1.0

### Actual behaviour

We recently upgraded our Shopware instance to version 6.5.7.1, under the assumption that BunnyCDN would be compatible with this version, as per the information provided here: 
![image](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/129844992/55e4bac4-b7ef-4492-982a-59f439ff12b0)

However, post-update, we are experiencing an issue where all our images are no longer displaying correctly, as shown in the screenshot: 

![image](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/129844992/d94c516c-81db-4e06-8692-eea25fa01a06)

Upon investigating, we noticed that Shopware's recent update includes changes in how image links are stored (as detailed in the [Shopware Upgrade Notes](https://github.com/shopware/shopware/blob/v6.5.7.0/UPGRADE-6.5.md#stored-media-path)). We suspect this might be the root cause of our issue.

Could you please help us understand if this is a known issue with the BunnyCDN integration? Do we need to re-upload all our images, or is there an alternative fix available? Any guidance on resolving this would be greatly appreciated.

Thank you for your assistance.

### Expected behaviour

Showing all Images

### Steps to Reproduce?

Update Shopware

**Comment by tinect** [comment]
you need to upload any existing media on your own just new media will be uploaded automatically. 

you might want to check the installation manual linked in the shopware store or the README:
https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#usage

**Comment by tinect** [comment]
just for info: this plugin does not manipulate the path of any media. it just changes the domain based in your setting.

**Comment by Lukaloco** [comment]
We used the plugin in the past and just updatet the shopware instance all media link changed.
the media files are uploaded in bunnycdn in the past.

**Comment by tinect** [comment]
check this please: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/issues/55#issuecomment-1821251181

**Comment by tinect** [comment]
@Lukaloco have you made any progress?

**Comment by Lukaloco** [comment]
Hello @tinect ,

Thank you very much for your tip! It turned out to be the solution: I added SHOPWARE_CDN_STRATEGY_DEFAULT=id to the .env file, and after the update, all the images were still there. Many thanks for that! I'd love to send you a case of beer to celebrate.

**Comment by tinect** [comment]
Hey @Lukaloco,

Currently, I have no idea. The image is saved on the storage of bunnyCDN? I mean, they support any query-string.

You might find support in community slack, but not by adding comments into closed issue.
