### ISSUE TITLE
BunnyCDN empty after "Purge Cache"?

### ISSUE THREAD

**Issue by WernerBuchert** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#58]
### Question

Hi,

we have a really strange problem. We initially uploaded the images to BunnyCDN via ftp.
Then we replaced images in the admin in the shopware store and deleted one extising image.
After that we pressed the "Purge Cache" Button at BunnyCDN and executed it, see the screenshot. Gradually all the images disappeared from BunnyCDN, so that in the end they were all deleted.
BunnyCDN support said that everything was OK on BunnyCDN and that a delete command or something similar must have come from the shopware, which would also be very strange.

Is there anything known in this regard that might be a bug in the plugin that could trigger this behavior?

Best regards, Werner Buchert.

<img width="1439" alt="purge_cache_button" src="https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/15101939/73b067af-5af8-4b3f-a6fb-cc301a1c2add">

**Comment by tinect** [comment]
Hey @WernerBuchert

I've heard about deleted files at bunnyNET the second time right now. For the moment, there is no known issue.
Calling `Purge Cache` does not call anything on the plugin or shop.

But, can you reproduce the issue in any way?

**Comment by WernerBuchert** [comment]
Hi,

okay, thank's for the info.

Unfortunately, we could not really reproduce this, but we will continue to work on it. 

Our store is not yet online, i.e. not accessible from outside, only within our company network. But that can't really be the problem, as the "Purge Cache" shouldn't call up anything?

Best regards, Werner Buchert.

**Comment by tinect** [comment]
From 1on1:
Empty files? oO
![image](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/135993/a7560dde-2d40-4231-94f9-da1c8c0a1e26)

**Comment by tinect** [comment]
I see a possibility that all the files could have been gone.

Therefore, I added a dedicated check in version 3.1.1.
