### ISSUE TITLE
Extremely slow upload times for images in the admin panel.

### ISSUE THREAD

**Issue by WernerBuchert** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#60]
### Question

Hi,

when we upload a picture in admin, it unfortunately takes more than 4 seconds to upload it. 
Here are 2 screenshots of a image that is not particularly large.
Somewhere in the plugin a lot of time is being wasted and unfortunately we don't know where at the moment.

I did a test with the 
https://github.com/PlatformCommunity/flysystem-bunnycdn
(that's the basis of the plugin, isn't it?), so I created a FileSystem object with the BunnyCDNAdapter as a parameter and then uploaded a file with $filesystem->writeStream, which took 0.36 seconds.
We already thought that our configuration in bunny.net was wrong, but if such a simple test is fast, we are not so sure anymore.

The fact that our store is not yet accessible from the outside (because it is not yet online) cannot be the reason, otherwise the simple test would not be fast either.

What could be the reason?

Or what is the easiest way to find out where these 4.9 seconds are being wasted?

Thank's and best regards, Werner Buchert.

<img width="1698" alt="upload1" src="https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/15101939/c4c8b715-1856-4f4e-a9bf-03f2a77e0542">
<img width="1701" alt="upload2" src="https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/15101939/854087d4-bdde-45b9-a813-e941a291d0ad">

**Comment by tinect** [comment]
Hey @WernerBuchert,

you are right, that the library is being used, while I'm contributing to it.

Could you please try uploading an image onto that system without bunnycdn and see the timings?

**Comment by WernerBuchert** [comment]
Hi,

oh, what a mess... you're right with your intuition
Without bunnycdn it's  also slow, 4.7 seconds.

The real problem is that we don't actually upload the product images via the admin, but via a process on the Shopware server, that is on the same machine, that is running Shopware, but which is just as slow.
The question is how to speed it up?
Everything is fast locally in my test environment on my laptop, but the server runs under 'localhost'.

But thank's for your answer.

**Comment by tinect** [comment]
Maybe a slow CPU or file system? 

Without debugging, I have no more ideas :-(

**Comment by WernerBuchert** [comment]
Yes, i know, I also thought about tmp file creation, I'll give that a try.
Otherwise, many thanks, it's not BunnyCDN's fault.

Best regards, Werner Buchert.
