### ISSUE TITLE
Assets on CDN

### ISSUE THREAD

**Issue by carstenjaksch** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#63]
### Question

Hi,

I want to continue work on my local Shopware installation, but suddenly the admin and storefront don't work anymore.

The storefront wants to load the file `theme/03696a03f230c3595e52271d5ea67b6f/css/all.css` from the CDN, but it is not there. You mention in the readme, that existing files in `public` need to be transferred manually.

Additionally, Devenv prints this error for the `/admin` request (blank page now). There are multiple errors with the same message, all for the favicon/touch icon:

```
ERROR	http.log.access.log0	handled request	{"request": {"remote_ip": "127.0.0.1", "remote_port": "62178", "client_ip": "127.0.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:8000", "uri": "/apple-touch-icon.png", "headers": {"Accept": ["*/*"], "Accept-Language": ["de-DE,de;q=0.9"], "Connection": ["keep-alive"], "Accept-Encoding": ["gzip, deflate"], "User-Agent": ["com.apple.WebKit.Networking/18614.2.9.1.12 CFNetwork/1399.4 Darwin/22.1.0"]}}, "bytes_read": 0, "user_id": "", "duration": 0.041664833, "size": 24271, "status": 500, "resp_headers": {"Vary": ["Accept-Encoding"], "Server": ["Caddy"], "X-Debug-Exception": ["Unable%20to%20find%20a%20matching%20sales%20channel%20for%20the%20request%3A%20%22http%3A%2F%2F127.0.0.1%3A8000%2Fapple-touch-icon.png%22.%20Please%20make%20sure%20the%20domain%20mapping%20is%20correct."], "X-Debug-Exception-File": ["%2FUsers%2Fcarstenjaksch%2Fdev%2Fshops%2Fvendor%2Fshopware%2Fstorefront%2FFramework%2FRouting%2FRequestTransformer.php:116"], "Status": ["500 Internal Server Error"], "X-Powered-By": ["PHP/8.2.15"], "Content-Type": ["text/html; charset=UTF-8"], "Content-Encoding": ["gzip"]}}
```

Is there any manual step I need to do in order to get asset files on the CDN?

And is there any way to disable the extension in the dev environment so that no asset changes swap into production?

**Comment by tinect** [comment]
Did you run `bin/console assets:install` and `bin/console theme:compile` afterward?
Background: Changing the storages in shopware does not move any file.

Did you read the info at the config fields?

Just disable the extension to make it not work in prod-storage. Maybe you could add any rule to your webserver to request any file not having locally from your cdns url.
Like this for apache:

```
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_URI} ^/media/
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ https://MY_CDN_ADDRESS/$1 [QSA,L]
  </IfModule>
```

**Comment by carstenjaksch** [comment]
There is no Shopware production environment at the moment. I guess disabling the extension for now is the best way. But ...

I get these errors:

`bin/console assets:install` or `bin/console plugin:deactivate FroshPlatformBunnycdnMediaStorage` (can't disable through admin, it is not available)

```
 [League\Flysystem\UnableToDeleteDirectory]                                                                                                                                      
  Unable to delete directory located at: bundles/framework. Client error: `DELETE https://storage.bunnycdn.com/[storageName]/bundles/framework/` resulted in a `404 Not Found` response:  
  {"HttpCode":404,"Message":"Object Not Found"} 
```

`bin/console theme:compile`

Throws a lot of deprecation warnings and seems to hang (no return to console input).

The last warning:

```
10:20:36 INFO      [php] User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\UrlGenerator::Shopware\Core\Content\Media\Pathname\UrlGenerator::getAbsoluteMediaUrl()" is deprecated and will be removed in v6.6.0.0. Use "Use AbstractUrlGenerator instead" instead.
[
  "exception" => ErrorException {
    #message: "User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\UrlGenerator::Shopware\Core\Content\Media\Pathname\UrlGenerator::getAbsoluteMediaUrl()" is deprecated and will be removed in v6.6.0.0. Use "Use AbstractUrlGenerator instead" instead."
    #code: 0
    #file: "./vendor/shopware/core/Framework/Feature.php"
    #line: 201
    #severity: E_USER_DEPRECATED
    trace: {
      ./vendor/shopware/core/Framework/Feature.php:201 { …}
      ./vendor/shopware/core/Content/Media/Pathname/UrlGenerator.php:54 { …}
      ./vendor/shopware/core/Content/Media/Core/Application/MediaUrlLoader.php:144 { …}
      ./vendor/symfony/event-dispatcher/EventDispatcher.php:260 { …}
      ./vendor/symfony/event-dispatcher/EventDispatcher.php:220 { …}
      ./vendor/symfony/event-dispatcher/EventDispatcher.php:56 { …}
      ./vendor/store.shopware.com/swagcommercial/src/Subscription/Framework/Event/SubscriptionEventDispatcher.php:27 { …}
      ./vendor/shopware/core/Content/Flow/Dispatching/FlowDispatcher.php:47 { …}
      ./vendor/shopware/core/Framework/Webhook/WebhookDispatcher.php:70 { …}
      ./vendor/shopware/core/Framework/Event/NestedEventDispatcher.php:31 { …}
      ./vendor/shopware/core/Framework/Event/NestedEventDispatcher.php:27 { …}
      ./vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139 { …}
      ./vendor/shopware/core/Framework/DataAbstractionLayer/EntityRepository.php:220 { …}
      ./vendor/shopware/core/Framework/DataAbstractionLayer/EntityRepository.php:240 { …}
      ./vendor/shopware/core/Framework/DataAbstractionLayer/EntityRepository.php:62 { …}
      ./vendor/shopware/storefront/Theme/ConfigLoader/DatabaseConfigLoader.php:279 { …}
      ./vendor/shopware/storefront/Theme/ConfigLoader/DatabaseConfigLoader.php:57 { …}
      ./vendor/shopware/storefront/Theme/ThemeService.php:73 { …}
      ./vendor/shopware/storefront/Theme/Command/ThemeCompileCommand.php:88 { …}
      ./vendor/symfony/console/Command/Command.php:326 { …}
      ./vendor/symfony/console/Application.php:1096 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:126 { …}
      ./vendor/symfony/console/Application.php:324 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:80 { …}
      ./vendor/symfony/console/Application.php:175 { …}
      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
      ./vendor/autoload_runtime.php:29 { …}
      ./bin/console:15 {
        › 
        › require_once __DIR__ . '/../vendor/autoload_runtime.php';
        › 
      }
    }
  }
]
```

**Comment by tinect** [comment]
The deprecation message is correct and has nothing to do with the plugin - just ignore it.

The error should not happen. Which shopware version and plugin version do you have installed?

**Comment by carstenjaksch** [comment]
6.5.8.2 Shopware
3.1 froshplatformbunnycdnmediastorage

**Comment by tinect** [comment]
Regarding the deprecations and hanging:

> Did you read the info at the config fields regarding "not recommended"? You might want create just a pull zone linked to your shop URL for assets and theme.
? While this will take years to compile and transfer.

**Comment by carstenjaksch** [comment]
Okay, can I change the config file in `var` and the changes take effect? Because I have no access to the admin currently.

**Comment by tinect** [comment]
yes, you can delete the file  within the var-folder and clear the cache from console.

**Comment by tinect** [comment]
after that, you can change the setting in the plugin config and save it again

**Comment by carstenjaksch** [comment]
Thank you! That worked. I disabled theme and assets for now, since there is no URL yet.

A quick question if you don't mind: I'd like to set a different CDN URL for different sales channels. But the inheritance does not work. If I choose a sales channel and click on the icon "remove inheritance", I can change the protocol, but not the URL. The same for all other fields. Is that not supported?

**Comment by tinect** [comment]
Yes, this is not supported within shopware without adding magic functions. I decided not to implement them, while it is hard to maintain it and the need is not enough. Maybe there are dedicated plugins where you can set different URLs per saleschannel.

**Comment by carstenjaksch** [comment]
Thanks, it is not that critical so I will deal with it.

**Comment by tinect** [comment]
PR on external project created to solve useless throwing of exception: https://github.com/PlatformCommunity/flysystem-bunnycdn/pull/72
