### ISSUE TITLE
class loader error on Install

### ISSUE THREAD

**Issue by ldehne-comcreate** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#65]
### PHP Version

8.2

### Shopware Version

6.5.8.6

### Plugin Version

3.1.2

### Actual behaviour

The class "Frosh\BunnycdnMediaStorage\FroshPlatformBunnycdnMediaStorage" is not found. Probably an class loader error. Check your plugin composer.json

### Expected behaviour

install working without any error.

### Steps to Reproduce?

I just installed the plugin on a freshly installed Shopware for use in this project, alongside BunnyCDN. In our other projects, BunnyCDN is working fine, but there it was installed in the past on older versions of Shopware.

**Comment by tinect** [comment]
How did you install it?

**Comment by ldehne-comcreate** [comment]
First Composer than tryed over zip and now over store on all the same Error

**Comment by ldehne-comcreate** [comment]
Okay, I've found a workaround: When I install a different plugin, the same error occurs, but the plugin I had installed before then works. So:

Install plugin -> Error
Install a different plugin -> Error
Activate first plugin -> Works flawlessly
Uninstall second plugin -> First plugin continues to work without any issues.

**Comment by tinect** [comment]
sounds like a `problem` with opcache 🤔

**Comment by tinect** [comment]
We'll close here due to inactivity.
