### ISSUE TITLE
Want plugin compatible with 6.5.0.0

### ISSUE THREAD

**Issue by priyaOza02** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#77]
### Question

We need a plugin compatible with version  6.5.0.0. We did check the version compatibility in the shop details. However, we did not find the plugin for version 6.5.0.0. 

![bunny-cdn-media-storage](https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/assets/129760392/dc0435dc-de34-4fcb-a3e6-eb3ddd8c5e31)

How to find the plugin which is compatible with 6.5.0.0 version?

**Comment by tinect** [comment]
Hei 👋 
try version 3.0.0.

**Comment by tinect** [comment]
FYI: I'll test a few things, but I think the next 3.3.1 will also be shopware 6.5.0 compatible again.
