### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#81]
### PHP Version

8.2

### Shopware Version

6.6.4.1

### Plugin Version

3.3.2

### Actual behaviour

When opening the plugin config an error is shown.
![Screenshot 2024-07-24 at 18-55-53 Shopware Administration](https://github.com/user-attachments/assets/3901957c-d05f-4700-a37e-969b8b4dfc63)

### Expected behaviour

open plugin config

### Steps to Reproduce?

open plugin config

**Comment by tinect** [comment]
This can mean some ways. It is difficult to assist you, while you don't leave any information.

What does this mean?
- did you download any zip and uploaded it to administration? When so, where did you get the zip?
- did you use the updater of plugin-manager?
- any other way?

**Comment by Tim-VL** [comment]
sorry, I was not clear.

Via the plugin-manager

**Comment by tinect** [comment]
is there any error in the devtools console?

**Comment by Tim-VL** [comment]
> is there any error in the devtools console? 
No that I can see, but I don't use devtools often.

> Could you please try running theme:compile?
Done, no change. Still the error

**Comment by tinect** [comment]
Ahhh, I remember, I added a warning there, while there is no more config to do.

This message should be printed:
![image](https://github.com/user-attachments/assets/87b00472-1632-408e-a977-ddff7f64db62)

I'll check, why the text is not shown soon.

**Comment by tinect** [comment]
It broke with shopware 6.6.3 which deprecates the used warning component.
I released plugin version 3.3.3, which solved it by posting the message as title.
