### ISSUE TITLE
How to migrate from 6.4 tot 6.6

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#82]
### Question

I've just updated our shop to 6.6 and still want to use BunnyCDN. I've configured the plugin, seens all good. images are not showing.

How to I connect the media again to Shopware?

**Comment by tinect** [comment]
Install the plugin and setting the correct config should be enough.

**Comment by Tim-VL** [comment]
the image path also looks strange to me

`https://test.DOMAIN.nl/shop/umeshu/cdn.DOMAIN.nl/media/a3/a0/ae/1603385112/joyo-umeshu-1.png?width=2000`

**Comment by tinect** [comment]
do you set https in front of the setting of cdn.DOMAIN.nl?

**Comment by Tim-VL** [comment]
> did you set https in front of the setting of cdn.DOMAIN.nl?

No, this was the issue for that the url then. Just did a assets:install and a cache:refresh... URL are now OK. thank you.
Still no media, but URL are now better.

Can it be that SW rebuild the thumbnails?

**Comment by tinect** [comment]
Are the URLs `better` or `correct`?

> Can it be that SW rebuild the thumbnails?
It depends on the real issue is based on your side. But you can try it by using the command `media:generate-thumbnails`

**Comment by tinect** [comment]
I will close here due to inactivity.
