### ISSUE TITLE
Infinite sales channel compile time

### ISSUE THREAD

**Issue by SimonBKohlschein** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#83]
### PHP Version

8.2.22

### Shopware Version

6.6.5.1

### Plugin Version

3.3.3

### Actual behaviour

Some sales channels don't compile the theme and instead just hang up, displaying the message 
`Compiling theme for sales channel for : _SALES_CHANNEL_ID_`
indefinitely.
Other sales channel compile just fine. The problem always occurs with the same sale channels. If I disable BunnyCDN for the theme system, but keep it enable for media all saleschannels compile just fine.

### Expected behaviour

The theme compiles in a reasonable amount of time for all sales channels.

### Steps to Reproduce?

I am unsure how this problem can be reproduced. Not all of our sales channels are having this problem, and the problem occurs even if no other plugins are enabled. The problem does not seem to occur on a default dockware installation. The problem occurs both if I use `bin/console theme:compile` to compile all themes and when I use `bin/console theme:compile -o _SALES_CHANNEL_ID_` to only compile the sales channel, which don't compile.

**Comment by tinect** [comment]
Hi @SimonBKohlschein 
this is no issue by this plugin, but with the system of theme in shopware.

Theme compilations are transferring huge number of files which will always takes some time. 

I recommend not transferring theme to external storage.

**Comment by SimonBKohlschein** [comment]
Hi @tinect,

the issue did not exist previously. While in the past, theme compiling with bunnycdn took 2–5 minutes (as opposed to 2–5 seconds without bunnycdn), now some sales channel have not finished compiling after an hour, while others still have a compile time of 2–5 minutes. Checking the file size of theme folder locally, it does not seem like it is bigger than before.

I am not sure if this problem started after a Shopware update or a bunnycdn plugin update, as I had theme transferring disabled for like a month, to speed up compile times.

**Comment by tinect** [comment]
It will have been worsen with an update, while shopware creates more files.

It is not the size of files, but the count of files. Could you please compare them?

Additionally, shopware saves a files with information of transferred files to speed it up afterwards.

it seems impossible to detect any speed or performance issue in this plugin while it just uses given APIs: Shopware and bunny.

**Comment by SimonBKohlschein** [comment]
The problem seems to occur both on Shopware 6.5.8.13 and 6.6.5.1 (we are currently testing switching to 6.6). With Shopware 6.6 there are more theme files due to the discontinuation of all.js, but with Shopware 6.5 with all plugins disabled there are actually fewer files in the theme folder than with the last known working Shopware instance backup with bunnycdn themes enabled.

Where can I find the "file with information of transferred files to speed it up"?

I don't think that this is a slowdown of the theme compilation. I think it is some kind of endless loop.

**Comment by tinect** [comment]
Currently, I am away from keyboard, so it is hard to find it for you. I recommend you to debug the theme compilation and asset installation.
